name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  placeholder:
    name: Placeholder
    runs-on: ubuntu-latest

    steps:
      - name: Exibir mensagem
        run: echo "CI configurado futuramente"